# Generated by Django 3.0.3 on 2020-04-04 07:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200404_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='haritaframe',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
