# Generated by Django 3.0.3 on 2020-04-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_slug'),
        ('home', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
