# Generated by Django 3.0.3 on 2020-04-04 07:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200331_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
