# Generated by Django 3.0.5 on 2020-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
