# Generated by Django 3.0.5 on 2020-05-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200526_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcard',
            name='day',
        ),
    ]
