# Generated by Django 3.0.5 on 2020-05-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_shopcard_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
